### ISSUE TITLE
Apresentação Final

### ISSUE THREAD

**Issue by angelogluz** [tricknp/mussum-2.0#15]
### Correções

- [x] Quais objetivos e requisitos foram concluídos? Colocar em negrito.

- [x] Pensar em destaques para tipos de mensagens diferentes

- [x] Implementar o "seguir" na unidade curricular

- [x] Disponibilizar acesso para os professores

### Sugestões/Considerações

- Primeiro apresentem o que foi feito, depois os trabalhos futuros
- Como o usuário loga ou valida o usuário?
- Sempre concluir os trabalhos apresentados
- A árvore do curso é gerenciável?

**Comment by tricknp** [comment]
#### Foi implementado o "seguir" na unidade curricular.
#### Funcionará da seguinte forma: 

#### Professor logado:

![captura de tela de 2018-07-03 21-02-27](https://user-images.githubusercontent.com/28790840/42249981-aa15bafe-7f04-11e8-9a0b-ba3b8404bcc1.png)
***

#### Aluno:
![captura de tela de 2018-07-03 21-01-46](https://user-images.githubusercontent.com/28790840/42249982-aa3facec-7f04-11e8-8550-f99ce23202e3.png)
***


#### Ao clicar no sino de notificações irá abrir um modal para o usuário por seu e-mail

![captura de tela de 2018-07-03 20-40-50](https://user-images.githubusercontent.com/28790840/42250034-f152939c-7f04-11e8-9481-07e468db0eea.png)
***

#### Após isso será enviado um e-mail conforme as atualizações do diretório selecionado.

#### Considerações: 
As notificações serão enviadas conforme a hierarquia selecionada no sino. Por exemplo: 

Se "seguir" um diretório que tenha outros diretórios filhos dentro, será enviado notificação a cada atualização nos diretórios filhos.

O ideal é seguir somente o diretório que realmente quer receber atualizações para que possa evitar spam no próprio e-mail.

**Comment by tricknp** [comment]
Acesso aos professores será disponibilizado após o projeto ir para produção. Será enviado um e-mail para cada professor com os devidos dados necessários.

**Comment by tricknp** [comment]
**Objetivos concluídos:** 

Todos os objetivos traçados foram concluídos.
